import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { useState, useEffect } from "react";

const Group: NextPage = () => {
  const router = useRouter();
  let { groupId } = router.query;
  if (Array.isArray(groupId)) {
    groupId = groupId.join("");
  }
  const { data: groupInfo, isLoading } = api.group.getOneById.useQuery(
    {
      groupId: groupId as string,
    },
    { enabled: !!groupId }
  );

  if (isLoading) return <div>Loading...</div>;

  if (!groupInfo) return <div>No group found</div>;

  return (
    <>
      <Head>
        <title>Supper Club</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen">
        <div className="m-auto">
          <h1 className="mb-4 text-center text-xl">{groupInfo.name}</h1>
          {/* <AdminControls /> */}
          {groupId && <ManageSuggestion groupId={groupId} />}
          {groupId && <MemberList groupId={groupId} />}
          <div className="mt-5 flex justify-center">
            <Link href="/">{"<- Go Home"}</Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Group;

const ManageSuggestion: React.FC<{ groupId: string }> = ({ groupId }) => {
  const group = api.group.getOneById.useQuery(
    {
      groupId: groupId,
    },
    { enabled: !!groupId }
  );
  const { data: sessionData } = useSession();
  const putSuggestion = api.group.putSuggestion.useMutation();
  const myCurrentSuggestion = () => {
    const me = group.data?.users.find((u) => u.userId === sessionData?.user.id);
    return me?.suggestion;
  };
  const [currentSuggestion, setCurrentSuggestion] = useState(
    myCurrentSuggestion()
  );
  const [tempSuggestion, setTempSuggestion] = useState("");

  useEffect(() => {
    const me = group.data?.users.find((u) => u.userId === sessionData?.user.id);
    setCurrentSuggestion(me?.suggestion);
  }, [group.data?.users, groupId, sessionData?.user.id]);

  return (
    <div className="flex justify-center">
      {currentSuggestion ? (
        <div className="flex items-center">
          <h2 className="text-lg">Current Suggestion: {currentSuggestion}</h2>
          <button
            onClick={(event) => {
              event.preventDefault();
              group.data &&
                putSuggestion.mutate({
                  suggestion: null,
                  groupId: group.data.id,
                });
              setCurrentSuggestion(null);
            }}
            className="rounded-full px-10 py-3 font-semibold no-underline transition hover:bg-black/10"
          >
            Reset
          </button>
        </div>
      ) : (
        <form
          onSubmit={(event) => {
            event.preventDefault();
            group.data &&
              putSuggestion.mutate({
                suggestion: tempSuggestion,
                groupId: group.data.id,
              });
            setCurrentSuggestion(tempSuggestion);
            setTempSuggestion("");
          }}
        >
          <input
            type="text"
            className="border-2 border-black"
            placeholder="restaurant suggestion"
            minLength={2}
            maxLength={36}
            value={tempSuggestion}
            onChange={(event) => setTempSuggestion(event.target.value)}
          />
          <button
            disabled={!tempSuggestion}
            type="submit"
            className="rounded-full px-10 py-3 font-semibold no-underline transition hover:bg-black/10"
          >
            Submit
          </button>
        </form>
      )}
    </div>
  );
};

const MemberList: React.FC<{ groupId: string }> = ({ groupId }) => {
  const group = api.group.getOneById.useQuery(
    {
      groupId: groupId,
    },
    { enabled: !!groupId }
  );

  return (
    <div>
      <h2 className="mt-4 text-lg">Members:</h2>
      {group.data &&
        group.data.users.map((groupuser) => (
          <div key={groupuser.user.id} className="flex justify-between">
            <div>{groupuser.user.name}</div>
            <div>{groupuser.points}</div>
          </div>
        ))}
    </div>
  );
};

// const AdminControls: React.FC<{ groupId: string }> = ({ groupId }) => {
//   const group = api.group.getOneById.useQuery(
//     {
//       groupId: groupId,
//     },
//     { enabled: !!groupId }
//   );

//   return (
//     <div>
//       <h2 className="mt-4 text-lg">Admin:</h2>
//       {group.data &&
//         group.data.users.map((groupuser) => (
//           <div key={groupuser.user.id} className="flex justify-between">
//             <div>{groupuser.user.name}</div>
//             <div>{groupuser.points}</div>
//           </div>
//         ))}
//     </div>
//   );
// };
