import { type NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";

import supperclubLogo from "../../public/supperclub_logo.svg";
import { useState } from "react";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Supper Club</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Image src={supperclubLogo} alt="Supper Club" />
          <div className="flex flex-col items-center gap-2">
            {sessionData && (
              <>
                <CreateGroup />
                <GroupBrowser />
              </>
            )}
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
      <button
        className="rounded-full px-10 py-3 font-semibold no-underline transition hover:bg-black/10"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};

const CreateGroup: React.FC = () => {
  const { data: sessionData } = useSession();
  const [name, setName] = useState("");

  const postGroup = api.group.postGroup.useMutation();
  return (
    <>
      {sessionData ? (
        <form
          onSubmit={(event) => {
            event.preventDefault();
            postGroup.mutate({
              name: name,
            });
            setName("");
          }}
        >
          <input
            type="text"
            className="border-2 border-black"
            placeholder="group name"
            minLength={2}
            maxLength={36}
            value={name}
            onChange={(event) => setName(event.target.value)}
          />
          <button
            type="submit"
            className="rounded-full px-10 py-3 font-semibold no-underline transition hover:bg-black/10"
          >
            Submit
          </button>
        </form>
      ) : (
        <></>
      )}
    </>
  );
};

const GroupBrowser: React.FC = () => {
  const groups = api.group.getAllForUser.useQuery();
  console.log(groups.data);
  return (
    <div>
      {groups.data &&
        groups.data.map((group) => (
          <div key={group.id}>
            <Link href={`/groups/${group.id}`}>{group.name}</Link>
          </div>
        ))}
    </div>
  );
};
